# Generated by Django 5.0.14 on 2026-03-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='presenza',
            name='unique_presenza_per_bambino_data',
        ),
    ]