# Generated by Django 5.0.14 on 2026-03-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_bambino_non_fotografabile'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrodiario',
            name='unique_registro_per_giorno',
        ),
        migrations.AlterUniqueTogether(
            name='registrodiario',
            unique_together={('bambino', 'data')},
        ),
    ]