# Generated by Django 5.0.14 on 2026-03-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_bambino_non_fotografabile'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menugiornaliero',
            name='unique_menu_per_data_sezione',
        ),
        migrations.RemoveConstraint(
            model_name='registropasto',
            name='unique_pasto_per_bambino_data',
        ),
        migrations.AlterUniqueTogether(
            name='menugiornaliero',
            unique_together={('data', 'sezione')},
        ),
        migrations.AlterUniqueTogether(
            name='registropasto',
            unique_together={('bambino', 'data')},
        ),
    ]